### ISSUE TITLE
Test https://github.com/wolfv/quetz/tree/testing

### ISSUE THREAD

**Issue by najose** [wolfv/quetz-docker#9]
@wolfv I have tried testing testing the changes in https://github.com/wolfv/quetz/tree/testing and noted my observations below.

## Observations
- Quetz crashes on handling an incoming request with the error "Google IAM is not configured". On checking the code [here](https://github.com/mamba-org/quetz/blob/2cbd6946d63f757c5ac16f3cd7bccf8c416440fe/plugins/quetz_googleiap/quetz_googleiap/middleware.py#L47-L50) - it supposed to raise the error if `[googleiam]` section is not configured in the config.toml. But in my testing the section is present in the config. On adding more debug statements into the code, it seems calling `config.configured_section('googleiam)` calls `config.get('googleiam')`  and this fails with the same error message as the ones seen in the annotated test failures in [this PR workflow run - (AttributeError: 'super' object has no attribute '__getattr__')](https://github.com/mamba-org/quetz/actions/runs/7116710813). Also  "Google IAM is not configured" seems to be raised in the [test failure annotations](https://github.com/mamba-org/quetz/actions/runs/7117537918) for [IAP middleware PR](https://github.com/mamba-org/quetz/pull/683/files)

## Testing environment
I have a built docker image using the below dockerfile and pushed it a publically accessible registry in case you want to inspect the image I'm using.

Image name: `us-east1-docker.pkg.dev/package-factory-sandbox/quetz-sdgr/quetz-testing:latest`

```Dockerfile
# Build conda environment
FROM condaforge/mambaforge:4.9.2-7 as conda

COPY environment.yml /tmp/environment.yml
RUN CONDA_COPY_ALWAYS=true mamba env create -p /env -f /tmp/environment.yml \
  && conda clean -afy

COPY . /code
RUN conda run -p /env python -m pip install --no-deps /code && \
    conda run -p /env python -m pip install /code/plugins/quetz_googleiap && \
    conda run -p /env python -m pip install xattr google-api-python-client google-auth-httplib2 google-auth-oauthlib quetz-frontend gcsfs

# Create image
FROM debian:buster-slim

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

COPY --from=conda /env /env

# Set WORKDIR to /tmp because quetz always creates a quetz.log file
# in the current directory
WORKDIR /tmp
ENV PATH /env/bin:$PATH
EXPOSE 8000

# The following command assumes that a deployment has been initialized
# in the /quetz-deployment volume
RUN apt-get update -y && \
    apt-get install curl -y

CMD ["quetz", "start", "/quetz-deployment", "--host", "0.0.0.0", "--port", "8000"]

```
The container startup script creates a deployment and starts Quetz:
```Helm
quetz create {{ $quetzDeploymentDirectory }} --copy-conf {{ $quetzConfigMapVolMountPath }}/{{ $quetzConfigFileName }} --exists-ok
quetz start {{ $quetzDeploymentDirectory }} --host 0.0.0.0 --port {{ $quetzContainerPort }}
```

### Config
```toml
[pamauthenticator]
# name for the provider, used in the login URL
provider = "pam"
# use the following to translate the Unix groups that
# users might belong to user role on Quetz server
admin_groups = ["quetz"]
maintainer_groups = []
user_groups = []

[sqlalchemy]
# In production we use postgres, but the issue can be reproduced with sqlite.
database_url = "sqlite:///./quetz.sqlite"

[session]
# openssl rand -hex 32. The below is not the secret that is actually used :)
secret = "984d92e652ba8ac0801a5a9c8f79b5b0bcf9f3461f65eda7c2867d29a3a276f9"
https_only = false

[logging]
level = "DEBUG"
file = "quetz.log"

[users]
admins = []

[storage]
soft_delete_channel = true
soft_delete_package = true

[googleiam]
server_admin_emails = [ "me@domain.com" ]

[profiling]
enable_sampling = false

[gcs]
project = "package-factory-sandbox"
bucket_prefix = "package-factory-"
bucket_suffix = "-packages"
cache_timeout = "0"
region="us-central1"
```

I'll add more observations in the GitHub issue as and when I find them. Please let me know when I can test again with the issues resolved in the testing branch.
